### ISSUE TITLE
Change name to App::LegendaryFlavor ?

### ISSUE THREAD

**Issue by leto** [wickline/legendary_flavor#2]
While I have always known this code as "game.pl", I would like for it to live on CPAN and Game.pm doesn't quite work. I started a branch for cpanification here:

https://github.com/leto/legendary_flavor/compare/cpanify

Comments?

**Comment by jckarter** [comment]
`App::Initech`

**Comment by wickline** [comment]
so now you see what happens when you propose a patch... I label you collaborator. This is legally binding.
